### ISSUE TITLE
Problem with TimeMachine share password

### ISSUE THREAD

**Issue by davezeking** [mbentley/docker-timemachine#45] opened 2020-07-02 10:57 UTC
Hi,

I've got the AFP container up and running (I need to use the AFP version as I have an older Mac on El Capitan that didn't seem to see the SMB container).  My Mac sees the AFP share in the Time Machine settings but when I try to select the disk I am prompted for a username and password, when I enter the default username and password ('timemachine' in lowercase) my system won't login to the share.

After running **docker logs timemachine** on my host (Ubuntu 18.04 server) I can see there is some kind of problem creating the accounts and changing the password:

> INFO: Group doesn't exist; creating...
> groupadd: GID '100' already exists
> INFO: User doesn't exist; creating...
> useradd: group 'timemachine' does not exist
> INFO: Using default password: timemachine
> chpasswd: (user timemachine) pam_chauthtok() failed, error:
> Authentication token manipulation error
> chpasswd: (line 1, user timemachine) password not changed
> INFO: INFO: CUSTOM_AFP_CONF=false; generating /etc/netatalk/afp.conf...
> INFO: SET_PERMISSIONS=false; not setting ownership and permissions for /opt/timemachine
> INFO: dbus PID exists; removing...
> removed '/var/run/dbus/pid'
> INFO: entrypoint complete; executing '/usr/bin/supervisord -c /etc/supervisord.conf'
> 2020-07-02 10:28:50,305 CRIT Set uid to user 0
> 2020-07-02 10:28:50,329 INFO supervisord started with pid 1
> 2020-07-02 10:28:50,723 INFO spawned: 'dbus' with pid 16
> 2020-07-02 10:28:50,724 INFO spawned: 'avahi-daemon' with pid 17
> 2020-07-02 10:28:50,726 INFO spawned: 'netatalk' with pid 18
> 2020-07-02 10:28:51,022 INFO exited: avahi-daemon (exit status 255; not expected)
> 2020-07-02 10:28:52,051 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2020-07-02 10:28:52,052 INFO spawned: 'avahi-daemon' with pid 22
> 2020-07-02 10:28:52,052 INFO success: netatalk entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2020-07-02 10:28:53,061 INFO success: avahi-daemon entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

I am creating my container using the following parameters:

docker network create -d macvlan --subnet=192.168.111.0/24 --gateway=192.168.111.1 -o parent=enp0s25 macvlan1

docker create \
  --restart unless-stopped \
  --name timemachine \
  --network macvlan1 \
  --ip 192.168.111.74 \
  -e HIDE_SHARES="yes" \
  -e LOG_LEVEL="info" \
  -e MIMIC_MODEL="TimeCapsule6,106" \
  -e TM_USERNAME="timemachine" \
  -e TM_GROUPNAME="timemachine" \
  -e TM_UID="1000" \
  -e TM_GID="100" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="false" \
  -e SHARE_NAME="TimeMachine" \
  -e SMB_PORT="445" \
  -e VOLUME_SIZE_LIMIT="0" \
  -v /home/myuser/docker/timemachine/backup:/opt/timemachine \
  -v /home/myuser/docker/timemachine/config/lib-samba:/var/lib/samba \
  -v /home/myuser/docker/timemachine/config/cache-samba:/var/cache/samba \
  -v /home/myuser/docker/timemachine/config/run-samba:/run/samba \
  mbentley/timemachine:afp

docker start timemachine

Any ideas why the default password isn't working? I've tried recreating the container without the PASSWORD, TM_USERNAME & TM_GROUPNAME parameters but I still cannot login.

**Comment by mbentley** [comment] 2020-07-02 11:15
Thanks for providing your run command.  Looks like there is something wrong with the entrypoint for the `afp` image; I was able to reproduce the issue.  Let me take a further look and will get back to you on that.

**Comment by mbentley** [comment] 2020-07-02 11:50
This should be fixed here shortly once the image is built on Docker Hub.  I added a check to see if the group exists, just with a different name and to just rename the existing group.

**Closed** 2020-07-02 11:49 UTC

**Comment by davezeking** [comment] 2020-07-02 13:25
Wow, that was quick thank you! I was trying to match the group with my 'users' group on the host - have I got the wrong thinking here? I'm quite new to docker so still a lot to learn!

**Comment by mbentley** [comment] 2020-07-02 14:07
Sure thing, happy to help.  I always appreciate folks pointing out things that could be better.  Regarding the UID/GID of your time machine users - it doesn't actually matter what the UID/GIDs are when it comes down to it.  The only reason to care would be when it comes to the host on which you are running time machine.  If users have access to the server itself and the UID/GID mapping is different than what is on the Docker host, then a user could potentially access someone else's time machine backup.  On my server, I just make sure to map the UID/GID so they match but if users don't have access to the Docker host, it is irrelevant.

**Comment by davezeking** [comment] 2020-07-02 14:51
Thanks for the extra info, I thought that's how it worked but always good to get a confirmation.
